#!/usr/bin/env bash
# Tenodera Bridge — remote host installer
#
# Usage:
#   Install:   sudo bash install-bridge.sh --gateway https://gw:9090 --token TOKEN
#   Uninstall: sudo bash install-bridge.sh --uninstall
#
# The bridge connects outbound to the gateway — no SSH keys or inbound ports needed.

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc/tenodera"

# ── Colors ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}==>${NC} $*"; }
ok()    { echo -e "${GREEN}==>${NC} $*"; }
fail()  { echo -e "${RED}ERROR:${NC} $*" >&2; exit 1; }

# ── Preflight ──────────────────────────────────────────────────────

if [ "$(id -u)" -ne 0 ]; then
  fail "This script must be run as root (use: sudo bash install-bridge.sh ...)"
fi

# ── Argument parsing ───────────────────────────────────────────────

GATEWAY_URL=""
TOKEN=""
ACCEPT_INSECURE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall)
      info "Removing tenodera-bridge..."
      systemctl stop tenodera-bridge 2>/dev/null || true
      systemctl disable tenodera-bridge 2>/dev/null || true
      rm -f /etc/systemd/system/tenodera-bridge.service
      systemctl daemon-reload 2>/dev/null || true
      rm -f "${INSTALL_DIR}/tenodera-bridge"
      ok "tenodera-bridge removed."
      exit 0
      ;;
    --gateway)
      GATEWAY_URL="$2"; shift 2;;
    --token)
      TOKEN="$2"; shift 2;;
    --accept-insecure)
      ACCEPT_INSECURE="1"; shift;;
    *)
      fail "Unknown argument: $1";;
  esac
done

if [ -z "$GATEWAY_URL" ] || [ -z "$TOKEN" ]; then
  fail "Usage: sudo bash install-bridge.sh --gateway https://gw:9090 --token TOKEN"
fi

# ── Download & build (skipped if binary already installed) ─────────

INSTALL_BIN="${INSTALL_DIR}/tenodera-bridge"

if [ -x "$INSTALL_BIN" ]; then
  info "tenodera-bridge already installed at ${INSTALL_BIN} — skipping build"
else
  REPO="ultherego/Tenodera"
  BRANCH="main"
  WORK_DIR="/tmp/tenodera-bridge-install"

  command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || \
    fail "curl or wget is required"

  info "Downloading bridge source..."
  rm -rf "$WORK_DIR"
  mkdir -p "$WORK_DIR"

  TARBALL_URL="https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz"

  if command -v curl >/dev/null 2>&1; then
    curl -sSfL "$TARBALL_URL" | tar xz -C "$WORK_DIR"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$TARBALL_URL" | tar xz -C "$WORK_DIR"
  fi

  EXTRACTED=$(ls -d "$WORK_DIR"/Tenodera-* 2>/dev/null | head -1)
  [ -z "$EXTRACTED" ] && fail "Failed to extract source archive"

  BRIDGE_DIR="$EXTRACTED/bridge"
  [ ! -d "$BRIDGE_DIR" ] || [ ! -d "$EXTRACTED/protocol" ] && \
    fail "Source directories not found"

  info "Building and installing tenodera-bridge (this may take a few minutes)..."
  cd "$BRIDGE_DIR"
  make all 2>&1

  info "Cleaning up build artifacts..."
  rm -rf "$WORK_DIR"
fi

# ── Write bridge config ────────────────────────────────────────────

info "Writing bridge config to ${CONF_DIR}/bridge.env..."
mkdir -p "$CONF_DIR"
chmod 755 "$CONF_DIR"

cat > "${CONF_DIR}/bridge.env" <<EOF
# Tenodera Bridge configuration
# Generated by install-bridge.sh — edit as needed

TENODERA_GATEWAY_URL=${GATEWAY_URL}
TENODERA_BRIDGE_TOKEN=${TOKEN}
EOF

if [ "$ACCEPT_INSECURE" = "1" ]; then
  echo "TENODERA_BRIDGE_ACCEPT_INSECURE=1" >> "${CONF_DIR}/bridge.env"
fi

chmod 600 "${CONF_DIR}/bridge.env"

# ── Enable and start ───────────────────────────────────────────────

info "Enabling and starting tenodera-bridge service..."
systemctl daemon-reload
systemctl enable --now tenodera-bridge

# ── Verify ────────────────────────────────────────────────────────

sleep 2
if systemctl is-active --quiet tenodera-bridge; then
  ok "tenodera-bridge is running"
else
  echo ""
  echo "  Service status:"
  systemctl status tenodera-bridge --no-pager || true
  fail "Service did not start — check logs: journalctl -u tenodera-bridge -n 30"
fi

# ── Cleanup ───────────────────────────────────────────────────────

info "Cleaning up build artifacts..."
rm -rf "$WORK_DIR"

ok "tenodera-bridge installed and running!"
echo ""
echo "  Config:  ${CONF_DIR}/bridge.env"
echo "  Logs:    journalctl -u tenodera-bridge -f"
echo "  Status:  systemctl status tenodera-bridge"
echo ""
echo "  The bridge will connect to: ${GATEWAY_URL}"
echo "  The host should appear online in the panel within seconds."
echo ""
