#!/usr/bin/env bash
# Tenodera Agent — remote host installer
#
# Usage:
#   Install (local):  sudo bash tenodera-agent.sh
#   Install (remote): sudo bash tenodera-agent.sh --gateway http://gw:9090
#   Uninstall:        sudo bash tenodera-agent.sh --uninstall
#
# The agent connects outbound to the gateway — no tokens, no SSH keys, no inbound ports needed.
# The host is registered automatically on first connection (identified by hostname).

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc/tenodera"

# ── Colors ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}==>${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC}  $*"; }
fail()  { echo -e "${RED}ERROR:${NC} $*" >&2; exit 1; }

# Strip per-crate cargo progress lines; warnings, errors, and "Finished" pass through.
cargo_quiet() {
  grep -Ev \
    "^   (Compiling|Fresh|Checking|Blocking|Running) |\
^    (Updating|Downloaded?) |\
^     Locking |\
^      Adding "
}

# ── Preflight ──────────────────────────────────────────────────────

if [ "$(id -u)" -ne 0 ]; then
  fail "This script must be run as root (use: sudo bash tenodera-agent.sh ...)"
fi

# ── Argument parsing ───────────────────────────────────────────────

GATEWAY_URL=""
ACCEPT_INSECURE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall)
      info "Removing tenodera-agent..."
      systemctl stop tenodera-agent 2>/dev/null || true
      systemctl disable tenodera-agent 2>/dev/null || true
      rm -f /etc/systemd/system/tenodera-agent.service
      systemctl daemon-reload 2>/dev/null || true
      rm -f "${INSTALL_DIR}/tenodera-agent"
      rm -f "${CONF_DIR}/agent.cnf"
      rmdir "${CONF_DIR}" 2>/dev/null || true
      rm -f /var/log/tenodera_audit.log
      ok "tenodera-agent removed."
      exit 0
      ;;
    --gateway)
      GATEWAY_URL="$2"; shift 2;;
    --accept-insecure)
      ACCEPT_INSECURE="1"; shift;;
    *)
      fail "Unknown argument: $1";;
  esac
done

# Default to local gateway if --gateway not provided
if [ -z "$GATEWAY_URL" ]; then
  GATEWAY_URL="http://127.0.0.1:9090"
  info "No --gateway specified — using local gateway: ${GATEWAY_URL}"
fi

# ── Download & build (skipped if binary already installed) ─────────

INSTALL_BIN="${INSTALL_DIR}/tenodera-agent"
WORK_DIR=""

SYSTEMD_SERVICE="/etc/systemd/system/tenodera-agent.service"

if [ -x "$INSTALL_BIN" ]; then
  info "tenodera-agent already installed at ${INSTALL_BIN} — skipping build"
  # Service file may be missing if the binary was copied manually.
  if [ ! -f "$SYSTEMD_SERVICE" ]; then
    info "Service file missing — installing tenodera-agent.service..."
    cat > "$SYSTEMD_SERVICE" <<'SVCEOF'
[Unit]
Description=Tenodera Agent
Documentation=https://github.com/ultherego/Tenodera
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/tenodera-agent
EnvironmentFile=-/etc/tenodera/agent.cnf

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF
  fi
else
  REPO="ultherego/Tenodera"
  BRANCH="main"
  WORK_DIR="/tmp/tenodera-agent-install"

  command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || \
    fail "curl or wget is required"

  info "Downloading agent source..."
  rm -rf "$WORK_DIR"
  mkdir -p "$WORK_DIR"

  TARBALL_URL="https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz"

  if command -v curl >/dev/null 2>&1; then
    curl -sSfL "$TARBALL_URL" | tar xz -C "$WORK_DIR"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$TARBALL_URL" | tar xz -C "$WORK_DIR"
  fi

  EXTRACTED=$(ls -d "$WORK_DIR"/Tenodera-* 2>/dev/null | head -1)
  [ -z "$EXTRACTED" ] && fail "Failed to extract source archive"

  AGENT_DIR="$EXTRACTED/agent"
  [ ! -d "$AGENT_DIR" ] || [ ! -d "$EXTRACTED/protocol" ] && \
    fail "Source directories not found"

  info "Building tenodera-agent"
  echo "     system deps  →  Rust compilation (~2-4 min)  →  install"
  cd "$AGENT_DIR"
  make all 2>&1 | cargo_quiet

  info "Cleaning up build artifacts..."
  rm -rf "$WORK_DIR"
fi

# ── Write agent config ────────────────────────────────────────────

info "Writing agent config to ${CONF_DIR}/agent.cnf..."
mkdir -p "$CONF_DIR"
chmod 755 "$CONF_DIR"

if [ "$ACCEPT_INSECURE" = "1" ]; then
  INSECURE_LINE="TENODERA_AGENT_ACCEPT_INSECURE=1"
else
  INSECURE_LINE="# TENODERA_AGENT_ACCEPT_INSECURE=1"
fi

cat > "${CONF_DIR}/agent.cnf" <<EOF
# Tenodera Agent configuration
# Generated by tenodera-agent.sh — edit as needed

TENODERA_GATEWAY_URL=${GATEWAY_URL}

# HTTPS/WSS: change TENODERA_GATEWAY_URL to https:// above. No other setting needed
# for CA-signed certs (e.g. Let's Encrypt). Uncomment below ONLY for self-signed certs.
${INSECURE_LINE}
EOF

chmod 600 "${CONF_DIR}/agent.cnf"

# ── Enable and start ───────────────────────────────────────────────

info "Enabling and starting tenodera-agent service..."
systemctl daemon-reload
systemctl enable tenodera-agent
# Always restart (not just enable --now) so the freshly-written agent.cnf
# is loaded even when make install already started the service with defaults.
systemctl restart tenodera-agent

# ── Verify ────────────────────────────────────────────────────────

sleep 2
if systemctl is-active --quiet tenodera-agent; then
  ok "tenodera-agent is running"
else
  echo ""
  echo "  Service status:"
  systemctl status tenodera-agent --no-pager || true
  fail "Service did not start — check logs: journalctl -u tenodera-agent -n 30"
fi

# ── Cleanup ───────────────────────────────────────────────────────

if [ -n "$WORK_DIR" ]; then
  info "Cleaning up build artifacts..."
  rm -rf "$WORK_DIR"
fi

ok "tenodera-agent installed and running!"
echo ""
echo "  Config:  ${CONF_DIR}/agent.cnf"
echo "  Logs:    journalctl -u tenodera-agent -f"
echo "  Status:  systemctl status tenodera-agent"
echo ""
echo "  The agent will connect to: ${GATEWAY_URL}"
echo "  The host should appear online in the panel within seconds."
echo ""
