#!/usr/bin/env bash
# Tenodera Bridge — remote host installer
#
# Usage:
#   Install (local):  sudo bash tenodera-bridge.sh
#   Install (remote): sudo bash tenodera-bridge.sh --gateway http://gw:9090
#   Uninstall:        sudo bash tenodera-bridge.sh --uninstall
#
# The bridge connects outbound to the gateway — no tokens, no SSH keys, no inbound ports needed.
# The host is registered automatically on first connection (identified by hostname).

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc/tenodera"

# ── Colors ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}==>${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC}  $*"; }
fail()  { echo -e "${RED}ERROR:${NC} $*" >&2; exit 1; }

# Strip per-crate cargo progress lines; warnings, errors, and "Finished" pass through.
cargo_quiet() {
  grep -Ev \
    "^   (Compiling|Fresh|Checking|Blocking|Running) |\
^    (Updating|Downloaded?) |\
^     Locking |\
^      Adding "
}

# ── Preflight ──────────────────────────────────────────────────────

if [ "$(id -u)" -ne 0 ]; then
  fail "This script must be run as root (use: sudo bash tenodera-bridge.sh ...)"
fi

# ── Argument parsing ───────────────────────────────────────────────

GATEWAY_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall)
      info "Removing tenodera-bridge..."
      systemctl stop tenodera-bridge 2>/dev/null || true
      systemctl disable tenodera-bridge 2>/dev/null || true
      rm -f /etc/systemd/system/tenodera-bridge.service
      systemctl daemon-reload 2>/dev/null || true
      rm -f "${INSTALL_DIR}/tenodera-bridge"
      rm -f "${CONF_DIR}/bridge.env"
      rmdir "${CONF_DIR}" 2>/dev/null || true
      rm -f /var/log/tenodera_audit.log
      ok "tenodera-bridge removed."
      exit 0
      ;;
    --gateway)
      GATEWAY_URL="$2"; shift 2;;
    --accept-insecure)
      shift;;  # kept for backward compat — ACCEPT_INSECURE is always written now
    *)
      fail "Unknown argument: $1";;
  esac
done

# Default to local gateway if --gateway not provided
if [ -z "$GATEWAY_URL" ]; then
  GATEWAY_URL="http://127.0.0.1:9090"
  info "No --gateway specified — using local gateway: ${GATEWAY_URL}"
fi

# ── Download & build (skipped if binary already installed) ─────────

INSTALL_BIN="${INSTALL_DIR}/tenodera-bridge"
WORK_DIR=""

SYSTEMD_SERVICE="/etc/systemd/system/tenodera-bridge.service"

if [ -x "$INSTALL_BIN" ]; then
  info "tenodera-bridge already installed at ${INSTALL_BIN} — skipping build"
  # Service file may be missing if the binary was copied manually.
  if [ ! -f "$SYSTEMD_SERVICE" ]; then
    info "Service file missing — installing tenodera-bridge.service..."
    cat > "$SYSTEMD_SERVICE" <<'SVCEOF'
[Unit]
Description=Tenodera Bridge Agent
Documentation=https://github.com/ultherego/Tenodera
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/tenodera-bridge
EnvironmentFile=-/etc/tenodera/bridge.env

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF
  fi
else
  REPO="ultherego/Tenodera"
  BRANCH="main"
  WORK_DIR="/tmp/tenodera-bridge-install"

  command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || \
    fail "curl or wget is required"

  info "Downloading bridge source..."
  rm -rf "$WORK_DIR"
  mkdir -p "$WORK_DIR"

  TARBALL_URL="https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz"

  if command -v curl >/dev/null 2>&1; then
    curl -sSfL "$TARBALL_URL" | tar xz -C "$WORK_DIR"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$TARBALL_URL" | tar xz -C "$WORK_DIR"
  fi

  EXTRACTED=$(ls -d "$WORK_DIR"/Tenodera-* 2>/dev/null | head -1)
  [ -z "$EXTRACTED" ] && fail "Failed to extract source archive"

  BRIDGE_DIR="$EXTRACTED/bridge"
  [ ! -d "$BRIDGE_DIR" ] || [ ! -d "$EXTRACTED/protocol" ] && \
    fail "Source directories not found"

  info "Building tenodera-bridge"
  echo "     system deps  →  Rust compilation (~2-4 min)  →  install"
  cd "$BRIDGE_DIR"
  make all 2>&1 | cargo_quiet

  info "Cleaning up build artifacts..."
  rm -rf "$WORK_DIR"
fi

# ── Write bridge config ────────────────────────────────────────────

info "Writing bridge config to ${CONF_DIR}/bridge.env..."
mkdir -p "$CONF_DIR"
chmod 755 "$CONF_DIR"

cat > "${CONF_DIR}/bridge.env" <<EOF
# Tenodera Bridge configuration
# Generated by tenodera-bridge.sh — edit as needed

TENODERA_GATEWAY_URL=${GATEWAY_URL}

# Skip TLS certificate verification — required when gateway uses a self-signed cert.
# Harmless when gateway_url starts with http:// (plain HTTP, no TLS).
TENODERA_BRIDGE_ACCEPT_INSECURE=1
EOF

chmod 600 "${CONF_DIR}/bridge.env"

# ── Enable and start ───────────────────────────────────────────────

info "Enabling and starting tenodera-bridge service..."
systemctl daemon-reload
systemctl enable --now tenodera-bridge

# ── Verify ────────────────────────────────────────────────────────

sleep 2
if systemctl is-active --quiet tenodera-bridge; then
  ok "tenodera-bridge is running"
else
  echo ""
  echo "  Service status:"
  systemctl status tenodera-bridge --no-pager || true
  fail "Service did not start — check logs: journalctl -u tenodera-bridge -n 30"
fi

# ── Cleanup ───────────────────────────────────────────────────────

if [ -n "$WORK_DIR" ]; then
  info "Cleaning up build artifacts..."
  rm -rf "$WORK_DIR"
fi

ok "tenodera-bridge installed and running!"
echo ""
echo "  Config:  ${CONF_DIR}/bridge.env"
echo "  Logs:    journalctl -u tenodera-bridge -f"
echo "  Status:  systemctl status tenodera-bridge"
echo ""
echo "  The bridge will connect to: ${GATEWAY_URL}"
echo "  The host should appear online in the panel within seconds."
echo ""
