#!/bin/sh
# Tenodera — one-shot Caddy reverse-proxy setup.
#
# Installs the latest Caddy from its official repository and writes a basic
# Caddyfile so the panel is served over HTTPS on the network while the gateway
# stays on 127.0.0.1. Runs as a systemd oneshot *after* package install — a
# maintainer script (postinst / %post) cannot install Caddy itself, because the
# outer `dpkg`/`dnf` transaction still holds the package-manager lock. Enabled at
# install time; it retries the install (waiting out that lock), then disables
# itself on success. Safe to re-run by hand: `sudo systemctl start tenodera-caddy-setup`.
set -u

UNIT=tenodera-caddy-setup.service
CADDYFILE=/etc/caddy/Caddyfile

log() { echo "tenodera-setup-caddy: $*"; }

# Install the latest Caddy from its official repo. Returns 0 if Caddy is present
# afterwards (including "already installed"), non-zero if the package manager was
# busy or the repo could not be reached — the caller retries in that case.
install_caddy() {
    command -v caddy >/dev/null 2>&1 && return 0
    if command -v apt-get >/dev/null 2>&1; then
        apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gnupg >/dev/null 2>&1 || true
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
            | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg 2>/dev/null || return 1
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
            > /etc/apt/sources.list.d/caddy-stable.list 2>/dev/null || return 1
        apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq caddy >/dev/null 2>&1
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y -q 'dnf-command(copr)' >/dev/null 2>&1 || true
        dnf copr enable -y '@caddy/caddy' >/dev/null 2>&1 || return 1
        dnf install -y -q caddy >/dev/null 2>&1
    elif command -v yum >/dev/null 2>&1; then
        yum install -y -q yum-plugin-copr >/dev/null 2>&1 || true
        yum copr enable -y '@caddy/caddy' >/dev/null 2>&1 || return 1
        yum install -y -q caddy >/dev/null 2>&1
    else
        return 1
    fi
    command -v caddy >/dev/null 2>&1
}

write_caddyfile() {
    # Serve on every non-loopback IPv4 address, so the panel is reachable on
    # whichever interface the operator uses (a multi-homed host has several IPs
    # and there is no way to guess which one they browse to). Caddy's internal CA
    # issues a self-signed cert covering them all.
    ADDRS=$(hostname -I | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | grep -v '^127\.' | paste -sd, - | sed 's/,/, /g')
    [ -n "$ADDRS" ] || ADDRS=":443"
    mkdir -p /etc/caddy
    if [ -f "$CADDYFILE" ] && ! grep -q 'generated by the Tenodera installer' "$CADDYFILE" 2>/dev/null; then
        log "$CADDYFILE already customised — leaving it as-is"
        return 0
    fi
    cat > "$CADDYFILE" <<EOF
# Reverse proxy generated by the Tenodera installer.
# Serves the panel over HTTPS on the network; the gateway stays on 127.0.0.1.
#
# Default: Caddy's internal CA on this host's IP(s), so browsers warn about an
# untrusted certificate (expected on a LAN — click through). For a real domain
# and a trusted certificate, replace the block below, e.g.:
#
#   panel.example.com {
#       reverse_proxy 127.0.0.1:9090         # Let's Encrypt cert, automatic
#       # tls /etc/caddy/certs/panel.crt /etc/caddy/certs/panel.key  # or your own
#       # header Strict-Transport-Security "max-age=31536000; includeSubDomains"
#   }
#
# Enable that HSTS header ONLY with a real CA-signed cert — never with the
# self-signed default below, or a browser that has seen HSTS will then refuse the
# untrusted cert with no click-through.
#
# Then: sudo systemctl reload caddy .  See DOCS.md -> Reverse proxy.

${ADDRS} {
    tls internal
    reverse_proxy 127.0.0.1:9090
}
EOF
    log "wrote $CADDYFILE — panel served at https://<host>"
}

# Retry the install: on a fresh package install the outer dpkg/dnf lock is still
# held for a few seconds after we start, so the first attempt may fail.
tries=0
while ! install_caddy; do
    tries=$((tries + 1))
    if [ "$tries" -ge 30 ]; then
        log "could not install Caddy automatically — panel stays on loopback (see DOCS 4.3)."
        # Leave the unit enabled so a later boot (with network) can retry.
        exit 0
    fi
    sleep 5
done

write_caddyfile
systemctl enable --now caddy >/dev/null 2>&1 || true
systemctl reload caddy >/dev/null 2>&1 || systemctl restart caddy >/dev/null 2>&1 || true
log "Caddy reverse proxy ready."

# Success — don't run again on every boot.
systemctl disable "$UNIT" >/dev/null 2>&1 || true
exit 0
